import ActionsBoard from '@/components/HomeComponents/ActionsBoard';
import { CampaignsAds } from '@/components/HomeComponents/CampaignsAds';
import { NewArrivalsSlider } from '@/components/HomeComponents/NewArrivalsSlider';
import { NotificationsBox } from '@/components/HomeComponents/NotificationsBox';
import { SalePerformance } from '@/components/HomeComponents/SalePerformance';
import { StoreBar } from '@/components/HomeComponents/StoreBar';
import Vehicles from '@/components/HomeComponents/Vehicles';
import { Layout } from '@/components/Layout/Layout';
import { fetchWord } from '@/lang/fetchWord';
import Head from 'next/head';
import Image from 'next/image';
import { useContext } from 'react';

import { LanguageContext } from './../context/LangContext';
import { EventsCalender } from '@/components/HomeComponents/EventsCalender';

export default function Home() {
  const { lang } = useContext(LanguageContext);
  return (
    <>
      <Head>
        <title>Sealal market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <StoreBar />
        <div className='container !my-4 md:!my-8'>
          <div className='flex gap-8 flex-wrap'>
            <div className='flex-1'>
              <SalePerformance />
              <ActionsBoard />
              <Vehicles />
              <CampaignsAds />
            </div>
            <div className='w-[587px] overflow-hidden'>
              <NewArrivalsSlider />
              <NotificationsBox />
              <EventsCalender />
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
