import { InputField } from "@/components/Forms/InputField";
import { Button } from "@/components/Global/Button/Button";
import EyeSlashIcon from "@/components/Icons/EyeSlashIcon";
import { fetchWord } from "@/lang/fetchWord";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useContext, useState } from "react";

import { LanguageContext } from "./../context/LangContext";

export default function Login() {
  const { lang } = useContext(LanguageContext);
  const [passwordType, setPasswordType] = useState("password");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const showPassword = () => {
    setPasswordType(prev => prev === 'password' ? 'text' : 'password')
  }

  const submit = (e) => {
    console.log(password, email)
    e.preventDefault();

  }
  return (
    <>
      <Head>
        <title>{fetchWord("login", lang)}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex items-center min-h-screen relative" >

        <Image
          className="object-contain absolute top-4 ltr:left-6 rtl:right-6"
          src="/images/logo.png"
          alt="register"
          height={70}
          width={130}
        />
        <Image
          className="object-contain"
          src="/images/authbanner.png"
          alt="register"
          height={480}
          width={420}
        />
        <div className="flex flex-col flex-1 items-center mb-8 overflow-auto">
          <div className="flex flex-col flex-1 mt-24 items-center w-full max-w-[500px]">
            <div className="flex flex-col w-full max-w-[500px]">
              <h1 className="text-2xl mb-2 text-center text-secondary capitalize font-semibold">
                {fetchWord("signin", lang)}
              </h1>
              <p className="text-center text-ptext mb-6">{fetchWord('signin_msg', lang)}</p>
              <form onSubmit={submit}>
                <InputField
                  name="email"
                  value={email}
                  label={fetchWord("email_phone_label", lang)}
                  placeholder={fetchWord("email_phone_label", lang)}
                  onChange={(e) => setEmail(e.target.value)}
                />
                <InputField
                  type={passwordType}
                  name="password"
                  value={password}
                  label={fetchWord("password_label", lang)}
                  placeholder={fetchWord("enter_password", lang)}
                  onChange={(e) => setPassword(e.target.value)}
                  iconEnd={<button type="button" onClick={showPassword} className="mt-1 ltr:mr-1 rtl:ml-1">
                    <EyeSlashIcon className={passwordType === 'text' ? 'text-primary' : ''} />
                  </button>}
                  icon
                />

                <Button classes="!p-3 block w-full">{fetchWord("login", lang)}</Button>
              </form>
              <Link href="/forgot-password" className=" text-[#009EF7] text-sm w-fit block ltr:ml-auto rtl:mr-auto mt-4">{fetchWord('forgot_password', lang)} {lang === 'ar' ? '؟' : '?'} </Link>
            </div>
          </div>
        </div>
      </div>

    </>
  );
}
