import { InputField } from "@/components/Forms/InputField";
import { Button } from "@/components/Global/Button/Button";
import EyeSlashIcon from "@/components/Icons/EyeSlashIcon";
import { SignInWith } from "@/components/SignInWith/SignInWith";
import SignupCompanyForm from "@/components/SignupCompanyForm/SignupCompanyForm";
import SignupCustomerForm from "@/components/SignupCustomerForm/SignupCustomerForm";
import SignupServiceForm from "@/components/SignupServiceForm/SignupServiceForm";
import SignupTabBar from "@/components/SignupTabBar/SignupTabBar";
import { fetchWord } from "@/lang/fetchWord";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useContext, useState } from "react";

import { LanguageContext } from "./../context/LangContext";

export default function Signup() {
  const { lang } = useContext(LanguageContext);
  const [passwordType, setPasswordType] = useState("password");
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState('');


  const showPassword = () => {
    setPasswordType(prev => prev === 'password' ? 'text' : 'password')
  }


  const submit = () => { };
  return (
    <>
      <Head>
        <title>{fetchWord("signup", lang)}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex items-center min-h-screen relative" >
        <Image
          className="object-contain absolute top-4 ltr:left-6 rtl:right-6"
          src="/images/logo.png"
          alt="register"
          height={70}
          width={130}
        />
        <Image
          className="object-contain"
          src="/images/authbanner2.png"
          alt="register"
          height={480}
          width={420}
        />
        <div className="flex flex-col flex-1 items-center mb-8 overflow-auto">
          <div className="flex flex-col flex-1 mt-24 items-center w-full max-w-[500px]">
            <div className="flex flex-col w-full max-w-[500px]">
              <h1 className="text-2xl mb-2 text-center text-secondary capitalize font-semibold">
                {fetchWord("signup", lang)}
              </h1>
              <p className="text-center text-ptext mb-6">{fetchWord('signup_msg', lang)}</p>
              <form onSubmit={submit}>
                <InputField
                  name="username"
                  value={username}
                  label={fetchWord("username_label", lang)}
                  placeholder={fetchWord("enter_your_name", lang)}
                  onChange={(e) => setUsername(e.target.value)}
                />
                <InputField
                  name="email"
                  value={email}
                  label={fetchWord("email_phone_label", lang)}
                  placeholder={fetchWord("email_phone_label", lang)}
                  onChange={(e) => setEmail(e.target.value)}
                />
                <div className="flex gap-4">
                  <InputField
                    type={passwordType}
                    name="password"
                    value={password}
                    label={fetchWord("password_label", lang)}
                    placeholder={fetchWord("enter_password", lang)}
                    onChange={(e) => setPassword(e.target.value)}
                    iconEnd={<button type="button" onClick={showPassword} className="mt-1 ltr:mr-1 rtl:ml-1">
                      <EyeSlashIcon className={passwordType === 'text' ? 'text-primary' : ''} />
                    </button>}
                  />
                  <InputField
                    type={passwordType}
                    name="confirmPassword"
                    value={confirmPassword}
                    label={fetchWord("confirm_password", lang)}
                    placeholder={fetchWord("confirm_password", lang)}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    iconEnd={<button type="button" onClick={showPassword} className="mt-1 ltr:mr-1 rtl:ml-1">
                      <EyeSlashIcon className={passwordType === 'text' ? 'text-primary' : ''} />
                    </button>}
                  />
                </div>

                <Button classes="!p-3 block w-full">{fetchWord("login", lang)}</Button>
              </form>
              <SignInWith />
              <div className="mt-4 text-center gap-1 flex justify-center">
                {fetchWord("have_account", lang)}
                <Link href="/signup" className=" text-primary">
                  {fetchWord("signin", lang)}
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>

    </>
  );
}
